Support Larva

diff --git a/bin/pmc-test-asset-build b/bin/pmc-test-asset-build
--- a/bin/pmc-test-asset-build
+++ b/bin/pmc-test-asset-build
@@ -25,12 +25,17 @@ pmc_run_npm_build() {
 					exit 1
 				fi
 
-				if [[ 0 != $(jq '.scripts.build|length' < package.json) ]]; then
+				if [[ 0 != $(jq '.scripts.build|length' < package.json) || 0 != $(jq '.scripts.prod|length' < package.json) ]]; then
 				  nvm install
 					npm config set unsafe-perm true
 					npm config set user 0
 					npm ci
-					npm run build || { echo 'Build Failed'; exit 1; }
+
+					if [[ 0 != $(jq '.scripts.build|length' < package.json) ]]; then
+						npm run build || { echo 'Build Failed'; exit 1; }
+					elif [ 0 != $(jq '.scripts.prod|length' < package.json) ]; then
+						npm run prod || { echo 'Build Failed'; exit 1; }
+					fi
 				fi
 			fi
 			popd
